# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constr_videokaart.xdc

# Block Designs: bd/PmodIPs/PmodIPs.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodIPs || ORIG_REF_NAME==PmodIPs} -quiet] -quiet

# IP: bd/PmodIPs/ip/PmodIPs_clk_wiz_0_0/PmodIPs_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodIPs_clk_wiz_0_0 || ORIG_REF_NAME==PmodIPs_clk_wiz_0_0} -quiet] -quiet

# IP: bd/PmodIPs/ip/PmodIPs_microblaze_0_0/PmodIPs_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodIPs_microblaze_0_0 || ORIG_REF_NAME==PmodIPs_microblaze_0_0} -quiet] -quiet

# IP: bd/PmodIPs/ip/PmodIPs_dlmb_v10_0/PmodIPs_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodIPs_dlmb_v10_0 || ORIG_REF_NAME==PmodIPs_dlmb_v10_0} -quiet] -quiet

# IP: bd/PmodIPs/ip/PmodIPs_ilmb_v10_0/PmodIPs_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodIPs_ilmb_v10_0 || ORIG_REF_NAME==PmodIPs_ilmb_v10_0} -quiet] -quiet

# IP: bd/PmodIPs/ip/PmodIPs_dlmb_bram_if_cntlr_0/PmodIPs_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodIPs_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==PmodIPs_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/PmodIPs/ip/PmodIPs_ilmb_bram_if_cntlr_0/PmodIPs_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodIPs_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==PmodIPs_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/PmodIPs/ip/PmodIPs_lmb_bram_0/PmodIPs_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodIPs_lmb_bram_0 || ORIG_REF_NAME==PmodIPs_lmb_bram_0} -quiet] -quiet

# IP: bd/PmodIPs/ip/PmodIPs_mdm_1_0/PmodIPs_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodIPs_mdm_1_0 || ORIG_REF_NAME==PmodIPs_mdm_1_0} -quiet] -quiet

# IP: bd/PmodIPs/ip/PmodIPs_rst_clk_wiz_0_100M_0/PmodIPs_rst_clk_wiz_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodIPs_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==PmodIPs_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/PmodIPs/ip/PmodIPs_axi_uartlite_0_0/PmodIPs_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodIPs_axi_uartlite_0_0 || ORIG_REF_NAME==PmodIPs_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/PmodIPs/ip/PmodIPs_xbar_0/PmodIPs_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodIPs_xbar_0 || ORIG_REF_NAME==PmodIPs_xbar_0} -quiet] -quiet

# IP: bd/PmodIPs/ip/PmodIPs_microblaze_0_axi_periph_0/PmodIPs_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodIPs_microblaze_0_axi_periph_0 || ORIG_REF_NAME==PmodIPs_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/PmodIPs/ip/PmodIPs_axi_gpio_0_0/PmodIPs_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodIPs_axi_gpio_0_0 || ORIG_REF_NAME==PmodIPs_axi_gpio_0_0} -quiet] -quiet

# IP: bd/PmodIPs/ip/PmodIPs_xlslice_0_2/PmodIPs_xlslice_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodIPs_xlslice_0_2 || ORIG_REF_NAME==PmodIPs_xlslice_0_2} -quiet] -quiet

# IP: bd/PmodIPs/ip/PmodIPs_xlslice_0_3/PmodIPs_xlslice_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodIPs_xlslice_0_3 || ORIG_REF_NAME==PmodIPs_xlslice_0_3} -quiet] -quiet

# IP: bd/PmodIPs/ip/PmodIPs_xlconcat_0_0/PmodIPs_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodIPs_xlconcat_0_0 || ORIG_REF_NAME==PmodIPs_xlconcat_0_0} -quiet] -quiet

# IP: bd/PmodIPs/ip/PmodIPs_IO_0/PmodIPs_IO_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodIPs_IO_0 || ORIG_REF_NAME==PmodIPs_IO_0} -quiet] -quiet

# IP: bd/PmodIPs/ip/PmodIPs_xlconcat_1_0/PmodIPs_xlconcat_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodIPs_xlconcat_1_0 || ORIG_REF_NAME==PmodIPs_xlconcat_1_0} -quiet] -quiet

# XDC: c:/github/RetroGame/VHDL/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/PmodIPs_ooc.xdc
