# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.runs/synth_1/Videokaart_full.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.cache/wt [current_project]
set_property parent.project_path C:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part_repo_paths {C:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.board} [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo c:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files C:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.srcs/sources_1/imports/RetroGame/Background.coe
add_files C:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.srcs/sources_1/imports/RetroGame/Logo.coe
read_vhdl -library xil_defaultlib {
  C:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.srcs/sources_1/imports/sources_1/imports/new/Dflipflop.vhd
  C:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.srcs/sources_1/imports/sources_1/new/InterfaceController.vhd
  C:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/hdl/PmodIPs_wrapper.vhd
  C:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.srcs/sources_1/imports/sources_1/imports/new/threeFlipFlop.vhd
  C:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.srcs/sources_1/imports/sources_1/imports/Progh/vga.vhd
  C:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.srcs/sources_1/imports/new/Videokaart_full.vhd
}
add_files C:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.srcs/sources_1/bd/PmodIPs/PmodIPs.bd
set_property used_in_implementation false [get_files -all c:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_clk_wiz_0_0/PmodIPs_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_clk_wiz_0_0/PmodIPs_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_clk_wiz_0_0/PmodIPs_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_microblaze_0_0/PmodIPs_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_microblaze_0_0/PmodIPs_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_microblaze_0_0/PmodIPs_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_dlmb_v10_0/PmodIPs_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_ilmb_v10_0/PmodIPs_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_dlmb_bram_if_cntlr_0/PmodIPs_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_ilmb_bram_if_cntlr_0/PmodIPs_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_lmb_bram_0/PmodIPs_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_mdm_1_0/PmodIPs_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_mdm_1_0/PmodIPs_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_rst_clk_wiz_0_100M_0/PmodIPs_rst_clk_wiz_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_rst_clk_wiz_0_100M_0/PmodIPs_rst_clk_wiz_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_rst_clk_wiz_0_100M_0/PmodIPs_rst_clk_wiz_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_uartlite_0_0/PmodIPs_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_uartlite_0_0/PmodIPs_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_uartlite_0_0/PmodIPs_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_xbar_0/PmodIPs_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_gpio_0_0/PmodIPs_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_gpio_0_0/PmodIPs_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_gpio_0_0/PmodIPs_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_IO_0/PmodIPs_IO_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_IO_0/PmodIPs_IO_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_IO_0/PmodIPs_IO_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/PmodIPs_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_microblaze_0_0/data/mb_bootloop_le.elf]

read_ip -quiet C:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.srcs/sources_1/ip/background/background.xci
set_property used_in_implementation false [get_files -all c:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/ip/background/background_ooc.xdc]

read_ip -quiet C:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.srcs/sources_1/ip/sprite63x63/sprite63x63.xci
set_property used_in_implementation false [get_files -all c:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/ip/sprite63x63/sprite63x63_ooc.xdc]

read_ip -quiet C:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.srcs/sources_1/ip/sprite31x31_2/sprite31x31_2.xci
set_property used_in_implementation false [get_files -all c:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/ip/sprite31x31_2/sprite31x31_2_ooc.xdc]

read_ip -quiet C:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.srcs/sources_1/ip/Sprite15x15_1/Sprite15x15_1.xci
set_property used_in_implementation false [get_files -all c:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/ip/Sprite15x15_1/Sprite15x15_1_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.srcs/constrs_1/new/Constr_videokaart.xdc
set_property used_in_implementation false [get_files C:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.srcs/constrs_1/new/Constr_videokaart.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.srcs/utils_1/imports/synth_1/Videokaart_full.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top Videokaart_full -part xc7a35tcpg236-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Videokaart_full.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Videokaart_full_utilization_synth.rpt -pb Videokaart_full_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
