# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/progh/VideoKaartMicroBlaze/VideoKaartMicroBlaze.srcs/sources_1/bd/PmodIPs/ip/PmodIPs_mdm_1_0/PmodIPs_mdm_1_0.xci
# IP: The module: 'PmodIPs_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/progh/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_mdm_1_0/PmodIPs_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PmodIPs_mdm_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/progh/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_mdm_1_0/PmodIPs_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'PmodIPs_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/progh/VideoKaartMicroBlaze/VideoKaartMicroBlaze.srcs/sources_1/bd/PmodIPs/ip/PmodIPs_mdm_1_0/PmodIPs_mdm_1_0.xci
# IP: The module: 'PmodIPs_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/progh/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_mdm_1_0/PmodIPs_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PmodIPs_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/progh/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_mdm_1_0/PmodIPs_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'PmodIPs_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
