# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.srcs/sources_1/ip/background/background.xci
# IP: The module: 'background' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/ip/background/background_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'background'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.srcs/sources_1/ip/background/background.xci
# IP: The module: 'background' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Joey/Downloads/VideoKaartMicroBlaze_third_special_editon/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/ip/background/background_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'background'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
