# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/github/RetroGame/VHDL/VideoKaartMicroBlaze/.Xil/Vivado-2708-Desktop-Joey/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a35tcpg236-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    c:/github/RetroGame/VHDL/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ipshared/c2c6
    c:/github/RetroGame/VHDL/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ipshared/ec67/hdl
    C:/github/RetroGame/VHDL/VideoKaartMicroBlaze/VideoKaartMicroBlaze.srcs/sources_1/ip/background
    C:/github/RetroGame/VHDL/VideoKaartMicroBlaze/VideoKaartMicroBlaze.srcs/sources_1/ip/sprite63x63
    C:/github/RetroGame/VHDL/VideoKaartMicroBlaze/VideoKaartMicroBlaze.srcs/sources_1/ip/sprite31x31_2
    C:/github/RetroGame/VHDL/VideoKaartMicroBlaze/VideoKaartMicroBlaze.srcs/sources_1/ip/Sprite15x15_1
  } {
      C:/Xilinx2/Vivado/2023.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      C:/Xilinx2/Vivado/2023.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    c:/github/RetroGame/VHDL/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ipshared/c2c6
    c:/github/RetroGame/VHDL/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ipshared/ec67/hdl
    C:/github/RetroGame/VHDL/VideoKaartMicroBlaze/VideoKaartMicroBlaze.srcs/sources_1/ip/background
    C:/github/RetroGame/VHDL/VideoKaartMicroBlaze/VideoKaartMicroBlaze.srcs/sources_1/ip/sprite63x63
    C:/github/RetroGame/VHDL/VideoKaartMicroBlaze/VideoKaartMicroBlaze.srcs/sources_1/ip/sprite31x31_2
    C:/github/RetroGame/VHDL/VideoKaartMicroBlaze/VideoKaartMicroBlaze.srcs/sources_1/ip/Sprite15x15_1
  } {
      c:/github/RetroGame/VHDL/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ipshared/217a/hdl/xlslice_v1_0_vl_rfs.v
      c:/github/RetroGame/VHDL/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_xlslice_0_2/synth/PmodIPs_xlslice_0_2.v
      c:/github/RetroGame/VHDL/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_xlslice_0_3/synth/PmodIPs_xlslice_0_3.v
      c:/github/RetroGame/VHDL/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ipshared/147b/hdl/xlconcat_v2_1_vl_rfs.v
      c:/github/RetroGame/VHDL/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_xlconcat_0_0/synth/PmodIPs_xlconcat_0_0.v
      c:/github/RetroGame/VHDL/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_xlconcat_1_0/synth/PmodIPs_xlconcat_1_0.v
    }
      rt::read_vhdl -lib xil_defaultlib {
      C:/github/RetroGame/VHDL/VideoKaartMicroBlaze/.Xil/Vivado-2708-Desktop-Joey/realtime/PmodIPs_clk_wiz_0_0_stub.vhdl
      C:/github/RetroGame/VHDL/VideoKaartMicroBlaze/.Xil/Vivado-2708-Desktop-Joey/realtime/PmodIPs_microblaze_0_0_stub.vhdl
      C:/github/RetroGame/VHDL/VideoKaartMicroBlaze/.Xil/Vivado-2708-Desktop-Joey/realtime/PmodIPs_dlmb_v10_0_stub.vhdl
      C:/github/RetroGame/VHDL/VideoKaartMicroBlaze/.Xil/Vivado-2708-Desktop-Joey/realtime/PmodIPs_ilmb_v10_0_stub.vhdl
      C:/github/RetroGame/VHDL/VideoKaartMicroBlaze/.Xil/Vivado-2708-Desktop-Joey/realtime/PmodIPs_dlmb_bram_if_cntlr_0_stub.vhdl
      C:/github/RetroGame/VHDL/VideoKaartMicroBlaze/.Xil/Vivado-2708-Desktop-Joey/realtime/PmodIPs_ilmb_bram_if_cntlr_0_stub.vhdl
      C:/github/RetroGame/VHDL/VideoKaartMicroBlaze/.Xil/Vivado-2708-Desktop-Joey/realtime/PmodIPs_lmb_bram_0_stub.vhdl
      C:/github/RetroGame/VHDL/VideoKaartMicroBlaze/.Xil/Vivado-2708-Desktop-Joey/realtime/PmodIPs_mdm_1_0_stub.vhdl
      C:/github/RetroGame/VHDL/VideoKaartMicroBlaze/.Xil/Vivado-2708-Desktop-Joey/realtime/PmodIPs_rst_clk_wiz_0_100M_0_stub.vhdl
      C:/github/RetroGame/VHDL/VideoKaartMicroBlaze/.Xil/Vivado-2708-Desktop-Joey/realtime/PmodIPs_axi_uartlite_0_0_stub.vhdl
      C:/github/RetroGame/VHDL/VideoKaartMicroBlaze/.Xil/Vivado-2708-Desktop-Joey/realtime/PmodIPs_xbar_0_stub.vhdl
      C:/github/RetroGame/VHDL/VideoKaartMicroBlaze/.Xil/Vivado-2708-Desktop-Joey/realtime/PmodIPs_axi_gpio_0_0_stub.vhdl
      C:/github/RetroGame/VHDL/VideoKaartMicroBlaze/.Xil/Vivado-2708-Desktop-Joey/realtime/PmodIPs_IO_0_stub.vhdl
      C:/github/RetroGame/VHDL/VideoKaartMicroBlaze/.Xil/Vivado-2708-Desktop-Joey/realtime/background_stub.vhdl
      C:/github/RetroGame/VHDL/VideoKaartMicroBlaze/.Xil/Vivado-2708-Desktop-Joey/realtime/sprite63x63_stub.vhdl
      C:/github/RetroGame/VHDL/VideoKaartMicroBlaze/.Xil/Vivado-2708-Desktop-Joey/realtime/sprite31x31_2_stub.vhdl
      C:/github/RetroGame/VHDL/VideoKaartMicroBlaze/.Xil/Vivado-2708-Desktop-Joey/realtime/Sprite15x15_1_stub.vhdl
      c:/github/RetroGame/VHDL/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/synth/PmodIPs.vhd
      C:/github/RetroGame/VHDL/VideoKaartMicroBlaze/VideoKaartMicroBlaze.srcs/sources_1/imports/sources_1/imports/new/Dflipflop.vhd
      C:/github/RetroGame/VHDL/VideoKaartMicroBlaze/VideoKaartMicroBlaze.srcs/sources_1/imports/sources_1/new/InterfaceController.vhd
      C:/github/RetroGame/VHDL/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/hdl/PmodIPs_wrapper.vhd
      C:/github/RetroGame/VHDL/VideoKaartMicroBlaze/VideoKaartMicroBlaze.srcs/sources_1/imports/sources_1/imports/new/threeFlipFlop.vhd
      C:/github/RetroGame/VHDL/VideoKaartMicroBlaze/VideoKaartMicroBlaze.srcs/sources_1/imports/sources_1/imports/Progh/vga.vhd
      C:/github/RetroGame/VHDL/VideoKaartMicroBlaze/VideoKaartMicroBlaze.srcs/sources_1/imports/new/Videokaart_full.vhd
    }
      rt::read_vhdl -lib xpm C:/Xilinx2/Vivado/2023.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top Videokaart_full
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/github/RetroGame/VHDL/VideoKaartMicroBlaze/.Xil/Vivado-2708-Desktop-Joey/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
