# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Progh/VideoKaartMicroBlaze_second_edition.xpr/VideoKaartMicroBlaze/VideoKaartMicroBlaze.srcs/sources_1/bd/PmodIPs/ip/PmodIPs_clk_wiz_0_0/PmodIPs_clk_wiz_0_0.xci
# IP: The module: 'PmodIPs_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Progh/VideoKaartMicroBlaze_second_edition.xpr/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_clk_wiz_0_0/PmodIPs_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PmodIPs_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Progh/VideoKaartMicroBlaze_second_edition.xpr/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_clk_wiz_0_0/PmodIPs_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PmodIPs_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Progh/VideoKaartMicroBlaze_second_edition.xpr/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_clk_wiz_0_0/PmodIPs_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PmodIPs_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Progh/VideoKaartMicroBlaze_second_edition.xpr/VideoKaartMicroBlaze/VideoKaartMicroBlaze.srcs/sources_1/bd/PmodIPs/ip/PmodIPs_clk_wiz_0_0/PmodIPs_clk_wiz_0_0.xci
# IP: The module: 'PmodIPs_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Progh/VideoKaartMicroBlaze_second_edition.xpr/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_clk_wiz_0_0/PmodIPs_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PmodIPs_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Progh/VideoKaartMicroBlaze_second_edition.xpr/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_clk_wiz_0_0/PmodIPs_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PmodIPs_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Progh/VideoKaartMicroBlaze_second_edition.xpr/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/bd/PmodIPs/ip/PmodIPs_clk_wiz_0_0/PmodIPs_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PmodIPs_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
