# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/progh/VideoKaartMicroBlaze/VideoKaartMicroBlaze.srcs/sources_1/ip/sprite63x63/sprite63x63.xci
# IP: The module: 'sprite63x63' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/progh/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/ip/sprite63x63/sprite63x63_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sprite63x63'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/progh/VideoKaartMicroBlaze/VideoKaartMicroBlaze.srcs/sources_1/ip/sprite63x63/sprite63x63.xci
# IP: The module: 'sprite63x63' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/progh/VideoKaartMicroBlaze/VideoKaartMicroBlaze.gen/sources_1/ip/sprite63x63/sprite63x63_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sprite63x63'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
